//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.269
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunToScore.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RunToScore.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hello!
        ///
        ///I&apos;m Tim, a French engineering student.
        ///I made this app in a weekend for a class project
        ///and I hope you enjoy it :)
        ///
        ///For any question / remark / bug report, feel
        ///free to contact me by email:.
        /// </summary>
        public static string aboutText1 {
            get {
                return ResourceManager.GetString("aboutText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I plan to release an update soon, including 
        ///worldwide ranking and Facebook sharing.
        ///
        ///Also, if you have any improvement ideas, tell me! .
        /// </summary>
        public static string aboutText2 {
            get {
                return ResourceManager.GetString("aboutText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PS: By the way, I&apos;m actually looking for
        ///an internship in back-end web development.
        ///You know how to find me... ;).
        /// </summary>
        public static string aboutText3 {
            get {
                return ResourceManager.GetString("aboutText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow GPS?.
        /// </summary>
        public static string AllowGPS {
            get {
                return ResourceManager.GetString("AllowGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To use this app you need to allow GPS usage. We do not use your GPS data on other purpose that recording your exercise tracking data. For more informations, you can read the privacy policy in the settings page..
        /// </summary>
        public static string AllowGPSText {
            get {
                return ResourceManager.GetString("AllowGPSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RunToScore.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your avg. speed is.
        /// </summary>
        public static string avgVitesse_before {
            get {
                return ResourceManager.GetString("avgVitesse_before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click to start.
        /// </summary>
        public static string clickToStart {
            get {
                return ResourceManager.GetString("clickToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You ran.
        /// </summary>
        public static string distance_before {
            get {
                return ResourceManager.GetString("distance_before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You ran for.
        /// </summary>
        public static string duration_before {
            get {
                return ResourceManager.GetString("duration_before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à History.
        /// </summary>
        public static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You lost around.
        /// </summary>
        public static string kCal_before {
            get {
                return ResourceManager.GetString("kCal_before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kilometers.
        /// </summary>
        public static string kilometers {
            get {
                return ResourceManager.GetString("kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Km.
        /// </summary>
        public static string km {
            get {
                return ResourceManager.GetString("km", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run.
        /// </summary>
        public static string mainPanorama1 {
            get {
                return ResourceManager.GetString("mainPanorama1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à History.
        /// </summary>
        public static string mainPanorama2 {
            get {
                return ResourceManager.GetString("mainPanorama2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ranking.
        /// </summary>
        public static string mainPanorama3 {
            get {
                return ResourceManager.GetString("mainPanorama3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Miles.
        /// </summary>
        public static string miles {
            get {
                return ResourceManager.GetString("miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à minutes.
        /// </summary>
        public static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow GPS.
        /// </summary>
        public static string modeGPS {
            get {
                return ResourceManager.GetString("modeGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run under lock screen.
        /// </summary>
        public static string modeLock {
            get {
                return ResourceManager.GetString("modeLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Town mode.
        /// </summary>
        public static string modeTown {
            get {
                return ResourceManager.GetString("modeTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à With town mode, pins on map are placed
        ///on streets rather than randomly.
        ///This use your data..
        /// </summary>
        public static string modeTownExplain {
            get {
                return ResourceManager.GetString("modeTownExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à in.
        /// </summary>
        public static string nbRun_before {
            get {
                return ResourceManager.GetString("nbRun_before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à run.
        /// </summary>
        public static string nbRun_unit {
            get {
                return ResourceManager.GetString("nbRun_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Run.
        /// </summary>
        public static string newRun {
            get {
                return ResourceManager.GetString("newRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You didn&apos;t run ... Yet.
        /// </summary>
        public static string noRunYet {
            get {
                return ResourceManager.GetString("noRunYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please Allow GPS.
        /// </summary>
        public static string PleaseAllowGPS {
            get {
                return ResourceManager.GetString("PleaseAllowGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à points.
        /// </summary>
        public static string points {
            get {
                return ResourceManager.GetString("points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You won.
        /// </summary>
        public static string points_before {
            get {
                return ResourceManager.GetString("points_before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Privacy policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your privacy is important.
        ///This application uses your location to measure
        ///your performance and track your route during
        ///your exercise.
        ///Your location data is not published and is only
        ///stored on your phone so you can have access to
        ///history.
        ///You may disable Location Services from
        ///RuntoScore settings section.
        ///
        ///If you have any question, feel free to ask at
        ///RunToScore@gmail.com.
        /// </summary>
        public static string PrivacyPolicyText {
            get {
                return ResourceManager.GetString("PrivacyPolicyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Privacy.
        /// </summary>
        public static string PrivacyPolicyTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Share by Mail.
        /// </summary>
        public static string ShareByMail {
            get {
                return ResourceManager.GetString("ShareByMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Share by Message.
        /// </summary>
        public static string ShareByMessage {
            get {
                return ResourceManager.GetString("ShareByMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Share on SkyDrive.
        /// </summary>
        public static string ShareBySkyDrive {
            get {
                return ResourceManager.GetString("ShareBySkyDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hi, look at my last run.
        /// </summary>
        public static string ShareMailSubject {
            get {
                return ResourceManager.GetString("ShareMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Share to your friends.
        /// </summary>
        public static string ShareOnFB {
            get {
                return ResourceManager.GetString("ShareOnFB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning.
        /// </summary>
        public static string StopReccordings {
            get {
                return ResourceManager.GetString("StopReccordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are about to stop reccordings. Continue?.
        /// </summary>
        public static string StopReccordingsText {
            get {
                return ResourceManager.GetString("StopReccordingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sorry, ranking is not yet available...
        ///But it&apos;ll come soon in an update.
        ///
        ///Stay tuned ;).
        /// </summary>
        public static string textRankingWait {
            get {
                return ResourceManager.GetString("textRankingWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Metric system.
        /// </summary>
        public static string titleMetric {
            get {
                return ResourceManager.GetString("titleMetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have.
        /// </summary>
        public static string youHave {
            get {
                return ResourceManager.GetString("youHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You ran.
        /// </summary>
        public static string youRan {
            get {
                return ResourceManager.GetString("youRan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à you ran for.
        /// </summary>
        public static string youRanFor {
            get {
                return ResourceManager.GetString("youRanFor", resourceCulture);
            }
        }
    }
}
